include ../Makefile.tests_common

USEMODULE += shell
FEATURES_REQUIRED += periph_timer
FEATURES_REQUIRED += periph_gpio

CFLAGS += -DRIOT_APPLICATION=\"$(APPLICATION)\"

include $(RIOTBASE)/Makefile.include
