APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))

# set and redirect default paths
TESTBASE ?= $(CURDIR)/../..
RIOTBASE ?= $(TESTBASE)/RIOT
BUILD_DIR ?= $(TESTBASE)/build


-include $(TESTBASE)/dist/etc/conf/$(BOARD).env
include $(TESTBASE)/dist/etc/conf/default.env

# Default timeout for serial connection to a board
export HIL_CMD_TIMEOUT

# Default wait time before connecting the serial
export HIL_CONNECT_WAIT

# Default wait time after reset in seconds
export HIL_RESET_WAIT

# suppress output
QUIET ?= 1
# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1
# expose extra metadata
CFLAGS += -DRIOT_APPLICATION=\"$(APPLICATION)\"

# Add the common folder for all common test helpers
EXTERNAL_MODULE_DIRS += $(TESTBASE)/utils/common
EXTERNAL_MODULE_DIRS += $(TESTBASE)/utils/sc_args

# All tests here _should_ use the test helpers
USEMODULE += test_helpers
USEMODULE += sc_args

# include RF specific settings
include $(TESTBASE)/dist/robotframework/Makefile.include
