APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))

# set and redirect default paths
TESTBASE ?= $(CURDIR)/../..
RIOTBASE ?= $(TESTBASE)/RIOT
BUILD_DIR ?= $(TESTBASE)/build
# Default timeout for serial connection to a board
CMD_TIMEOUT ?= 1
export CMD_TIMEOUT
# Default wait time before connecting the serial
CONNECT_WAIT ?= 0
export CONNECT_WAIT
# suppress output
QUIET ?= 1
# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1
# expose extra metadata
CFLAGS += -DRIOT_APPLICATION=\"$(APPLICATION)\"

# Add the common folder for all common test helpers
EXTERNAL_MODULE_DIRS += $(TESTBASE)/tests/common

# All tests here _should_ use the test helpers
USEMODULE += test_helpers

# include RF specific settings
include $(TESTBASE)/dist/robotframework/Makefile.include
