include ../Makefile.tests_common

USEMODULE += shell
FEATURES_REQUIRED += periph_timer
FEATURES_REQUIRED += periph_gpio

export HIL_DUT_GPIO0_PORT
export HIL_DUT_GPIO0_PIN
export HIL_PERIPH_TIMER_DEV
export HIL_PERIPH_TIMER_HZ

include $(RIOTBASE)/Makefile.include
