include ../Makefile.tests_common

FEATURES_REQUIRED = periph_gpio

USEMODULE += shell

export HIL_DUT_GPIO0_PORT
export HIL_DUT_GPIO0_PIN
export HIL_DUT_GPIO1_PORT
export HIL_DUT_GPIO1_PIN
export HIL_DUT_GPIO2_PORT
export HIL_DUT_GPIO2_PIN

include $(RIOTBASE)/Makefile.include
